<?php 

return  [
        'contact' => [
            'phone' => '059.113.114',
            'signup_advice' => 'ĐĂNG KÝ TƯ VẤN',
            'ask' => 'HỎI ĐÁP',
            'abc' => 'Nhap ngu'
        ],
        'stage' => [
            'pending' => 'Đang chờ',
            'inprogress' => 'Trong quá trình',
            'done' => 'Xong'
        ],
        'news_types' => [
            'LEOPALACE21' => 'LEOPALACE21',
            'order' => '他の物件',
            'Musashi' => '武蔵コーポレーション株式会社',
        ],
        'shapes' => [
            'poly' => 'Đa giác',
            'rect' => 'vuông',
            'circle' => 'Tròn'
        ],
        'priceRange' => [
            'min' => 200,
            'max' => 1000000000
        ],
        'priceDropdown' => [
            '200-1.000 円' => '200;1000',
            '1.001-5.000 円' => '1001;5000',
            '5.001-1.0000 円' => '5001;10000',
            '10.001-20.000 円' => '10001;20000',
            '20.001-50.000 円' => '20001;50000',
            '50.001-100.000 円' => '50001;100000',
        ],
        'acreageRange'=> [
            'min' => 0,
            'max' => 50000
        ],
        'acreageDropdown' => [
            '0-100' => '0;100',
            '101-200' => '101;200',
            '201-300' => '301;400',
            '301-400' => '301;400',
            '401-500' => '401;500'
        ],
        'defautuser' => "(1, 'Mr. Admin', 'admin@admin.com', NULL, $2y$10\$RtVmSU6Bot9emNoca.eUxuMUDVf4PwOEgxJnDeywo0aMATFn5gA.u', 1, 'default.png', 1, 'v1WweocPEYlY95n0vyWrI5csuBA8lTg4lq9LcPoEx27G6YZGBv5bYqKq8qwg', '2020-07-18 05:27:53', '2020-07-24 18:22:40')",
        'text' => [
            'home'=> 'ホーム',// trang chủ 
            'staff' => "スタッフ",// nhân viên
            'views' => 'ビュー', // Lượt xem
            'comments' => 'コメント', // Bình Luận
            'leave_a_reply' => '返信を残す', // để lại bình luận cho bài viết 
            'enter_your_name_here' => 'ここにあなたの名前を入力してください', // nhập tên của bạn <<ô nhập tên>>
            'enter_your_email_here' => 'あなたのメールアドレスをここに入力してください', //nhập email của bạn <<ô nhập email>>
            'enter_your_website_here' => 'ここにあなたのウェブサイトを入力してください', // nhập website của bạn (không bắt buộc) <<ô nhập web site>>
            'enter_your_comment_here' => 'ここにコメントを入力してください', // Viết bình luận của bạn <<ô nhập bình luận>>
            'post_comment' => 'コメントを投稿', // Đăng bình luận <<nút đăng bình luận>>
            'leave_cmt_success' => 'コメントを残してください！', //Đăng bình luận thành công << cái này là khi khách đăng bình luận thành công sẽ nhảy ra cái thông báo>>
            'info_submit_success'=> '情報送信の成功', // Gửi thông tin liên hệ thành công <<cái này là khi khách đặt lịch hẹn với mình thành công thì sẽ hiện lên cái thông báo này nè>>
            'monday_to_friday' => '月曜日から土曜日まで',// làm việc từ thứ 2 đến thứ 6
            'send_us_your_query_anytime' => 'いつでもお問い合わせください！', // gửi yêu cầu của bạn đến chung tôi bất kỳ lúc nào
            'category' => 'カテゴリー', // thể loại <<để bán hay để thuê>>
            'district' => '地区', // tỉnh, thành phố
            'enter_search_keywork'=>'フリーワード検索',
            'enter_search_keywork_placeholder'=> '地名, 駅名, 建物名',
            'status' => '状態', // trạng thái
            'type' => '間取タイプ', // cũng là thể loại
            'price'     =>'価格', // giá 
            'management_costs'=> '管理費', // giá tiền quản lý
            'acreage'=>'面積', // diện tích
            'floors' => '床',       // tầng
            'rooms' => '部屋',      // phòng
            'bathrooms' => 'バスルーム', // phòng tắm
            'bedrooms' => 'ベッドルーム', // phòng ngủ
            'host_name' => 'ホスト名', // tên chủ nhà
            'yen' => '円',      // yên
            'address' => '住所', // địa chỉ
            'go_detail' => '詳細を見る', // xem chi tiết <<nút xem chi tiết>>
            'contract_now' => '今すぐ契約', // liên hệ ngay <<nút liên hệ>>
            'tags_cloud' => 'タグクラウド', // tags
            'post_categories'=> '投稿カテゴリ', // các mục bài viết    
            'properties_in_various_cities'=>'さまざまな都市のプロパティ', // <<mấy cái này khẩu hiệu tào lao thích đổi câu nào cũng đc>> 
            'extremely_love'=>'環境にやさしいシステムを非常に愛している人。', // <<mấy cái này khẩu hiệu tào lao thích đổi câu nào cũng đc>> 
            'make_an_appointment'=>'予約する', // đặt lịch hẹn
            'name' => '名前', // Tên của bạn <<mấy cái này là form liên hệ cũng giống form comment phía trên , bấm vào liên hệ bất động sản để xem trang này>>
            'enter_your_name' => 'あなたの名前を入力してください', // nhập tên của bạn
            'email' => 'Eメール',
            'enter_your_email'=>'メールアドレスを入力',
            'request_asset' => 'アセットをリクエストする',
            'enter_subject'=> '件名を入力してください',
            'subject'=> '件名',
            'phone_number'=>'電話番号',
            'enter_your_phone_number'=>'電話番号を入力してください',
            'appointment'=>'予定',
            'enter_appointment_date'=> '予約日を入力してください',
            'message'=>'メッセージ',
            'enter_message'=> 'メッセージを入力してください',
            'send_message'=> 'メッセージを送る',
            'vacancy_room_rent_rental'=>'空　室　賃　貸　物　件', // <<mấy cái này Tiêu đề trang chủ tào lao thích đổi câu nào cũng đc>>
            'new_arrival_vacant_room_rent_rental'=> '新 着 空 室 賃 貸 物 件',// <<mấy cái này Tiêu đề trang chủ tào lao thích đổi câu nào cũng đc>>
            'someone_who_loves_the_environment_friendly_system_very_much'=>'環境にやさしいシステムを非常に気に入っている人。', // <<mấy cái này khẩu hiệu tào lao thích đổi câu nào cũng đc>> 
            'about_us'=> '会社概要', // Hồ sơ công ty <<tab trên trang chủ>>
            'property'=>'業務内容',// Nội dung kinh doanh <<tab trên trang chủ>>
            'agents'=>'従業員紹介',// Giới thiệu nhân viên <<tab trên trang chủ>>
            'contract_flow'=>'物件の情報',//  Quy trình hợp đồng <<tab trên trang chủ>>
            'contact'=>'お問い合せ', // Liên hệ chúng tôi
            'slogan'=> 'お客様の利益と満足を第一に考え、価値ある資産づくりと良質な物件のご提供をお手伝いいたします。',// slogan treen video
            'new_vacant_rental_property'=>'新 着 空 室 賃 貸 物 件',// <<mấy cái này Tiêu đề trang chủ tào lao thích đổi câu nào cũng đc>>
            'room_count'=>'部屋数',
            'floor_count'=>'フロア数',
            '1_room'=>'一つの部屋があります',
            '2_room'=>'二つの部屋があります',
            '3_room'=>'三つの部屋があります',
            '1_floor'=> '一階あり',
            '2_floor'=> '二階あり',
            '3_floor'=> '三階あり',
            'price_range'=> '賃料',
            'area_range'=>'面積',
            'search'=>'探す',
            'post_comment'=>'コメントを投稿',
            'asset_detail'=>'物件の詳細情報',
            'map'=>'地図',
            'created_at'=> '作成日',
            'description'=> '説明',
            'writer' => '作家',
            'is_foreign_nationality_consultation'=> "外国籍相談可",
            'is_newly_built_properties'=> "新築物件",
            'free_first_months'=>'フリーレント',
            'greater_than_x_month'=>'ヶ月以上',
            'bus_station_distance'=> '駅徒歩',
            'lower_than_x_minute'=>'分未満',
            'receiving_time'=>'入居可能時期',
            'lower_than_x_weeks'=>'週間未満',
            'all'=> 'すべて',
            'yes'=> 'はい',
            'no' => '番号',
            'minute'=> '分',
            'year' => '年',
            'train'=> '駅',
            'bus_station'=>'駅',
            'key_money' => '礼金（敷引・償却金）',
            'deposit'=>'敷金（保証金）',
            'floor_plan'=>'間取り',
            'year_built'=> '築年',
            'management_costs'=>'管理費・共益費',
            'no_result'=>'検索結果が0件です。検索条件を再度入力してください。',
            'contract_flow_1'=>'Ⅰ.不動産賃貸、売買、管理、仲介',
            'contract_flow_2'=>'Ⅱ.高度人材ご提供、技能実習生紹介',
            'contract_flow_3'=>'Ⅲ.アジア直通物品販売',
        ]
];